import fs from 'fs/promises'
import path from 'path'
import yaml from 'js-yaml'
import { loadApps } from './registry'
import { listContainers } from './dockerClient'
import type { PortMapping } from './registry'

const OVERRIDE_HEADER =
  '# Auto-generated by Harbormaster — do not edit manually'

const registryKey = '__harbormaster_portRegistry__'
if (!(globalThis as Record<string, unknown>)[registryKey]) {
  ;(globalThis as Record<string, unknown>)[registryKey] = new Map<
    number,
    string
  >()
}
const portRegistry = (globalThis as Record<string, unknown>)[
  registryKey
] as Map<number, string>

// ---------- Compose Parsing ----------

export async function parseComposePorts(
  composeDir: string,
): Promise<PortMapping[]> {
  const composePath = path.join(composeDir, 'docker-compose.yml')
  let content: string
  try {
    content = await fs.readFile(composePath, 'utf8')
  } catch {
    return []
  }

  const doc = yaml.load(content) as Record<string, Record<string, unknown>> | null
  if (!doc || !doc.services) return []

  const ports: PortMapping[] = []
  for (const [serviceName, service] of Object.entries(
    doc.services as Record<string, Record<string, unknown>>,
  )) {
    if (!service.ports || !Array.isArray(service.ports)) continue
    for (const entry of service.ports) {
      const parsed = parsePortEntry(String(entry))
      if (parsed) {
        parsed.service = serviceName
        ports.push(parsed)
      }
    }
  }
  return ports
}

function parsePortEntry(entry: string): PortMapping | null {
  let protocol = 'tcp'
  const protoMatch = entry.match(/\/(tcp|udp)$/i)
  if (protoMatch) {
    protocol = protoMatch[1].toLowerCase()
    entry = entry.slice(0, -protoMatch[0].length)
  }

  const parts = entry.split(':')

  if (parts.length === 1) {
    const containerPort = parseInt(parts[0], 10)
    if (isNaN(containerPort)) return null
    return {
      containerPort,
      hostPort: 0,
      protocol,
      overridden: false,
    }
  }

  if (parts.length === 2) {
    const hostPort = parseInt(parts[0], 10)
    const containerPort = parseInt(parts[1], 10)
    if (isNaN(hostPort) || isNaN(containerPort)) return null
    return { containerPort, hostPort, protocol, overridden: false }
  }

  if (parts.length === 3) {
    const hostPort = parseInt(parts[1], 10)
    const containerPort = parseInt(parts[2], 10)
    if (isNaN(hostPort) || isNaN(containerPort)) return null
    return { containerPort, hostPort, protocol, overridden: false }
  }

  return null
}

// ---------- Port Registry ----------

export async function buildRegistry(): Promise<void> {
  portRegistry.clear()

  try {
    const apps = await loadApps()
    for (const app of apps) {
      if (!app.ports) continue
      for (const p of app.ports) {
        if (p.hostPort) portRegistry.set(p.hostPort, app.id)
      }
    }
  } catch {}

  await scanExternalPorts()
}

export async function scanExternalPorts(): Promise<void> {
  for (const [port, owner] of portRegistry) {
    if (typeof owner === 'string' && owner.startsWith('external:')) {
      portRegistry.delete(port)
    }
  }

  try {
    const containers = await listContainers()
    const apps = await loadApps()
    const managedIds = new Set(apps.map((a) => a.id))

    for (const container of containers) {
      const name = (container.Names?.[0] || '').replace(/^\//, '')
      if (managedIds.has(name)) continue

      const ports = container.Ports || []
      for (const p of ports) {
        if (p.PublicPort) {
          portRegistry.set(p.PublicPort, `external:${name}`)
        }
      }
    }
  } catch {}
}

export function getPortMap(): Record<number, string> {
  const result: Record<number, string> = {}
  for (const [port, owner] of portRegistry) {
    result[port] = owner
  }
  return result
}

export function isPortAvailable(
  hostPort: number,
  excludeAppId?: string,
): boolean {
  if (!portRegistry.has(hostPort)) return true
  return portRegistry.get(hostPort) === excludeAppId
}

export function getPortOwner(hostPort: number): string | null {
  return portRegistry.get(hostPort) || null
}

export function findAvailablePort(startFrom: number): number {
  let port = Math.max(startFrom, 1025)
  while (portRegistry.has(port)) port++
  return port
}

export function getAvailablePorts(base: number, count: number): number[] {
  const result: number[] = []
  let port = Math.max(base || 1025, 1025)
  while (result.length < count) {
    if (!portRegistry.has(port)) result.push(port)
    port++
  }
  return result
}

// ---------- Conflict Resolution ----------

interface ResolveResult {
  ports: PortMapping[]
  conflicts: Array<{
    containerPort: number
    requested: number | null
    assigned: number
    owner?: string
    reason: string
  }>
}

export function resolvePorts(
  ports: PortMapping[],
  appId: string,
): ResolveResult {
  const resolved: PortMapping[] = []
  const conflicts: ResolveResult['conflicts'] = []

  for (const p of ports) {
    const entry = { ...p }

    if (!entry.hostPort) {
      entry.hostPort = findAvailablePort(entry.containerPort)
      entry.overridden = true
      conflicts.push({
        containerPort: entry.containerPort,
        requested: null,
        assigned: entry.hostPort,
        reason: 'No host port specified, auto-assigned',
      })
    } else if (!isPortAvailable(entry.hostPort, appId)) {
      const owner = getPortOwner(entry.hostPort)
      const original = entry.hostPort
      entry.hostPort = findAvailablePort(entry.hostPort + 1)
      entry.overridden = true
      conflicts.push({
        containerPort: entry.containerPort,
        requested: original,
        assigned: entry.hostPort,
        owner: owner || undefined,
        reason: `Port ${original} is in use by ${owner}`,
      })
    }

    resolved.push(entry)
  }

  return { ports: resolved, conflicts }
}

// ---------- Registry Management ----------

export function registerAppPorts(appId: string, ports: PortMapping[]): void {
  unregisterAppPorts(appId)
  for (const p of ports) {
    if (p.hostPort) portRegistry.set(p.hostPort, appId)
  }
}

export function unregisterAppPorts(appId: string): void {
  for (const [port, owner] of portRegistry) {
    if (owner === appId) portRegistry.delete(port)
  }
}

// ---------- Override File Management ----------

export async function writeOverrideFile(
  composeDir: string,
  ports: PortMapping[],
): Promise<{ written: boolean; conflict?: boolean; message?: string }> {
  const hasOverrides = ports.some((p) => p.overridden)

  if (!hasOverrides) {
    await deleteOverrideFile(composeDir)
    return { written: false }
  }

  const conflict = await checkOverrideConflict(composeDir)
  if (conflict) {
    return { written: false, conflict: true, message: conflict }
  }

  const byService: Record<string, PortMapping[]> = {}
  for (const p of ports) {
    const svc = p.service || 'app'
    if (!byService[svc]) byService[svc] = []
    byService[svc].push(p)
  }

  const services: Record<string, { ports: string[] }> = {}
  for (const [svc, svcPorts] of Object.entries(byService)) {
    services[svc] = {
      ports: svcPorts.map((p) => {
        const proto = p.protocol && p.protocol !== 'tcp' ? `/${p.protocol}` : ''
        return `${p.hostPort}:${p.containerPort}${proto}`
      }),
    }
  }

  const doc = { services }
  const yamlStr = yaml.dump(doc, { lineWidth: -1 })
  const content = `${OVERRIDE_HEADER}\n# Edit port mappings via the Harbormaster dashboard\n${yamlStr}`

  const overridePath = path.join(composeDir, 'docker-compose.override.yml')
  await fs.writeFile(overridePath, content)
  return { written: true }
}

export async function deleteOverrideFile(
  composeDir: string,
): Promise<{ deleted: boolean; reason?: string }> {
  const overridePath = path.join(composeDir, 'docker-compose.override.yml')
  try {
    const content = await fs.readFile(overridePath, 'utf8')
    if (!content.includes(OVERRIDE_HEADER)) {
      return {
        deleted: false,
        reason: 'Override file was not created by Harbormaster',
      }
    }
    await fs.unlink(overridePath)
    return { deleted: true }
  } catch {
    return { deleted: false, reason: 'No override file exists' }
  }
}

export async function checkOverrideConflict(
  composeDir: string,
): Promise<string | null> {
  const overridePath = path.join(composeDir, 'docker-compose.override.yml')
  try {
    const content = await fs.readFile(overridePath, 'utf8')
    if (!content.includes(OVERRIDE_HEADER)) {
      return "A docker-compose.override.yml exists in this app's directory that was not created by Harbormaster. Port overrides cannot be applied until it is removed."
    }
  } catch {}
  return null
}

// ---------- Startup ----------

let scanInterval: ReturnType<typeof setInterval> | null = null

export function startPortScanning(): void {
  buildRegistry()
  scanInterval = setInterval(scanExternalPorts, 60_000)
}

export function stopPortScanning(): void {
  if (scanInterval) {
    clearInterval(scanInterval)
    scanInterval = null
  }
}
