/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsNewRouteImport } from './routes/apps.new'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'
import { Route as AppsAppIdEditRouteImport } from './routes/apps.$appId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNewRoute = AppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdEditRoute = AppsAppIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppsAppIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/apps/new': typeof AppsNewRoute
  '/apps/$appId/edit': typeof AppsAppIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/apps/new': typeof AppsNewRoute
  '/apps/$appId/edit': typeof AppsAppIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/apps/new': typeof AppsNewRoute
  '/apps/$appId/edit': typeof AppsAppIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ports'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/apps/$appId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ports'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/apps/$appId/edit'
  id:
    | '__root__'
    | '/'
    | '/ports'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/apps/$appId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortsRoute: typeof PortsRoute
  SettingsRoute: typeof SettingsRoute
  AppsAppIdRoute: typeof AppsAppIdRouteWithChildren
  AppsNewRoute: typeof AppsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/new': {
      id: '/apps/new'
      path: '/apps/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId/edit': {
      id: '/apps/$appId/edit'
      path: '/edit'
      fullPath: '/apps/$appId/edit'
      preLoaderRoute: typeof AppsAppIdEditRouteImport
      parentRoute: typeof AppsAppIdRoute
    }
  }
}

interface AppsAppIdRouteChildren {
  AppsAppIdEditRoute: typeof AppsAppIdEditRoute
}

const AppsAppIdRouteChildren: AppsAppIdRouteChildren = {
  AppsAppIdEditRoute: AppsAppIdEditRoute,
}

const AppsAppIdRouteWithChildren = AppsAppIdRoute._addFileChildren(
  AppsAppIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortsRoute: PortsRoute,
  SettingsRoute: SettingsRoute,
  AppsAppIdRoute: AppsAppIdRouteWithChildren,
  AppsNewRoute: AppsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
